# Generated by Django 5.1.2 on 2024-11-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('none', 'none'), ('admin', 'admin'), ('manager', 'manager'), ('staff', 'staff')], default='none', max_length=10),
        ),
    ]
