# Generated by Django 5.1.2 on 2024-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approve_status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected')], max_length=20, null=True),
        ),
    ]
